---
- hosts: localhost
  name: Install homebrew, rvm and packages needed for IOS CI
  vars:
    rvm1_rubies:
      - ruby-2.2.2
    homebrew_installed_packages:
      - gpg
      - carthage
      - ideviceinstaller
      - imagemagick
      - ghostscript
  roles:
    - { role: geerlingguy.homebrew, tags: brew }
    - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True, rvm1_install_flags: '--user-install', rvm1_install_path: '/Users/{{local_username.stdout}}/.rvm', rvm1_user: '{{local_username.stdout}}' }
  pre_tasks:
    - name: get my username
      command: whoami
      register: local_username
      tags: ruby

  post_tasks:
    - name: install gems with rvm
      command: bash -lc "gem install {{ item }}"
      with_items:
        - activesupport
        - fastlane
        - scan
        - gym
        - xcpretty
      tags: ruby
